### ISSUE TITLE
When using area first display will be recorded always

### ISSUE THREAD

**Issue by flash-me** [vkohaupt/vokoscreenNG#76] opened 2020-04-16 17:38 UTC
Hi,

I have a setup of two displays: 
1. 2560x1440
2. 3440x1440

and when I select an area on the second screen, the first screen will be recorded anway.

Log:
<details>
  <summary>Click to expand</summary>
<code>
[vokoscreenNG] Version: 3.0.1
[vokoscreenNG] Locale: en_US
[vokoscreenNG] Log from: 2020-04-16 19:03:46
[vokoscreenNG] Country: UnitedStates
[vokoscreenNG] Qt: 5.9.5
[vokoscreenNG] GStreamer 1.14.5
[vokoscreenNG] Operating system: Ubuntu Core 18
[vokoscreenNG] CPU Architecture: x86_64
[vokoscreenNG] vokoscreenNG running as: xcb client
[vokoscreenNG] vokoscreenNG running on: x11
[vokoscreenNG] Desktop: XFCE
[vokoscreenNG] Icon-Theme: Adwaita
[vokoscreenNG] Styles: (Windows, Fusion)
[vokoscreenNG] Qt-PluginsPath:      /usr/lib/x86_64-linux-gnu/qt5/plugins
[vokoscreenNG] Qt-TranslationsPath: /usr/share/qt5/translations
[vokoscreenNG] Qt-LibraryPath:      /usr/lib/x86_64-linux-gnu
[vokoscreenNG] Settings: /home/flash/snap/vokoscreen-ng/33/.config/vokoscreenNG/vokoscreenNG.ini
[vokoscreenNG] Log: /home/flash/snap/vokoscreen-ng/33/.config/vokoscreenNG/log/2020_04_16_19_03_43.log
[vokoscreenNG] CompositingManager running: true

[vokoscreenNG] [PulseAudio] Found: Monitor of GP104 High Definition Audio Controller Digital Stereo (HDMI 3) Device: alsa_output.pci-0000_02_00.1.hdmi-stereo-extra2.monitor
[vokoscreenNG] [PulseAudio] Found: Monitor of Built-in Audio Analog Surround 5.1 Device: alsa_output.pci-0000_00_1f.3.analog-surround-51.monitor

[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] - vaapih264enc
[vokoscreenNG] - vaapimpeg2enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc

[vokoscreenNG] + ximagesrc
[vokoscreenNG] + pulsesrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] + h264parse
[vokoscreenNG] + adder

[vokoscreenNG] Name from screen:  HDMI-0
[vokoscreenNG] Screen available desktop width : 3440
[vokoscreenNG] Screen available desktop height: 1440
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 99
[vokoscreenNG] Screen orientation Qt::ScreenOrientation(LandscapeOrientation)
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  
[vokoscreenNG] Manufactur from screen:  
[vokoscreenNG] SerialNumber from screen:  
[vokoscreenNG] ItemText in Combobox: HDMI-0 :  3440 x 1440
[vokoscreenNG] ItemData in Combobox: x=2560 y=0 with=3440 height=1440

[vokoscreenNG] Name from screen:  DP-2
[vokoscreenNG] Screen available desktop width : 2560
[vokoscreenNG] Screen available desktop height: 1440
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 119
[vokoscreenNG] Screen orientation Qt::ScreenOrientation(LandscapeOrientation)
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  
[vokoscreenNG] Manufactur from screen:  
[vokoscreenNG] SerialNumber from screen:  
[vokoscreenNG] ItemText in Combobox: DP-2 :  2560 x 1440
[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=2560 height=1440

[vokoscreenNG] ExtensionsPath: /home/flash/snap/vokoscreen-ng/33/vokoscreen_extensions/
[vokoscreenNG] No library for extension found
 
[vokoscreenNG] Desktop session is a X11 session
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] - vaapih264enc
[vokoscreenNG] - vaapimpeg2enc
[vokoscreenNG] + lamemp3enc
[vokoscreenNG] + opusenc

radioButtonScreencastFullscreen=false
radioButtonScreencastWindow=false
radioButtonScreencastArea=true
checkBoxCameraOnOff=false
checkBoxCameraMirrorVertical=false
checkBoxCameraMirrorHorizontal=false
checkBoxCameraInvert=false
checkBoxCameraGray=false
checkBoxCameraMono=false
checkBoxCameraWindowFrame=false
checkboxAudioDevice-0=false
checkboxAudioDevice-1=false
checkBoxShowInSystray=true
checkBoxShowInSystrayAlternative=true
checkBoxMinimizedWhenRecordingStarts=false
checkBoxStartsMinimized=false
checkBoxResetAtNextStart=false
checkBoxLookForUpdates=true
checkBoxMouseCursorOnOff=false
checkBoxScale=false
checkBoxMagnifier=false
comboBoxCamera=
comboBoxOnlineHelp=Automatically
comboBoxFormat=mp4
comboBoxVideoCodec=x264
comboBoxx264Preset=superfast
comboBoxAudioCodec=mp3
comboBoxAreaSize=320 x 200 CGA 16 : 10
comboBoxScale=320 x 200 CGA 16 : 10
comboBoxScreencastScreen=HDMI-0 :  3440 x 1440
sliderVolume=70
sliderVideo=0
sliderCameraWindowSize=2
sliderHour=0
sliderMinute=0
sliderStopRecordingAfterHouers=0
sliderStopRecordingAfterMinutes=0
sliderStopRecordingAfterSeconds=15
sliderLimitOfFreeDiskSpace=250
sliderShowInSystrayAlternative=48
sliderSecondWaitBeforeRecording=1
sliderX264=17
sliderOpenh264=23
sliderFrames=25
sliderScreencastCountDown=0
sliderMagnification=2
lineEditVideoPath=/home/flash/Videos
[vokoscreenNG] Start record with: ximagesrc display-name=:0.0 use-damage=false show-pointer=true startx=613 starty=106 endx=2554 endy=1431 ! capsfilter caps=video/x-raw,framerate=25/1 ! videoconvert ! videorate ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=8 ! video/x-h264, profile=baseline ! mp4mux name=mux ! filesink location=/home/flash/Videos/vokoscreenNG-2020-04-16_19-30-34.mp4
 
gst-launch-1.0 -e \
    ximagesrc display-name=:0.0 use-damage=false show-pointer=true startx=613 starty=106 endx=2554 endy=1431 \
        ! capsfilter caps=video/x-raw,framerate=25/1 \
        ! videoconvert \
        ! videorate \
        ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=8 \
        ! video/x-h264, profile=baseline \
        ! mp4mux name=mux \
        ! filesink location=/home/flash/Videos/vokoscreenNG-2020-04-16_19-30-34.mp4

[vokoscreenNG] Stop record
radioButtonScreencastFullscreen=false
radioButtonScreencastWindow=true
radioButtonScreencastArea=false
checkBoxCameraOnOff=false
checkBoxCameraMirrorVertical=false
checkBoxCameraMirrorHorizontal=false
checkBoxCameraInvert=false
checkBoxCameraGray=false
checkBoxCameraMono=false
checkBoxCameraWindowFrame=false
checkBoxMouseCursorOnOff=false
checkboxAudioDevice-0=false
checkboxAudioDevice-1=false
checkBoxShowInSystray=true
checkBoxShowInSystrayAlternative=true
checkBoxMinimizedWhenRecordingStarts=false
checkBoxStartsMinimized=false
checkBoxResetAtNextStart=false
checkBoxLookForUpdates=true
checkBoxScale=false
checkBoxMagnifier=false
comboBoxCamera=
comboBoxFormat=mp4
comboBoxVideoCodec=x264
comboBoxx264Preset=superfast
comboBoxAudioCodec=mp3
comboBoxOnlineHelp=Automatically
comboBoxAreaSize=320 x 200 CGA 16 : 10
comboBoxScale=320 x 200 CGA 16 : 10
comboBoxScreencastScreen=DP-2 :  2560 x 1440
sliderCameraWindowSize=2
sliderVolume=70
sliderVideo=0
sliderX264=17
sliderOpenh264=23
sliderFrames=25
sliderLimitOfFreeDiskSpace=250
sliderShowInSystrayAlternative=48
sliderSecondWaitBeforeRecording=1
sliderHour=0
sliderMinute=0
sliderStopRecordingAfterHouers=0
sliderStopRecordingAfterMinutes=0
sliderStopRecordingAfterSeconds=15
sliderScreencastCountDown=0
sliderMagnification=2
lineEditVideoPath=/home/flash/Videos
[vokoscreenNG] Start record with: ximagesrc display-name=:0.0 use-damage=false show-pointer=true xid=71303169 ! capsfilter caps=video/x-raw,framerate=25/1 ! videoconvert ! videorate ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=8 ! video/x-h264, profile=baseline ! mp4mux name=mux ! filesink location=/home/flash/Videos/vokoscreenNG-2020-04-16_19-33-22.mp4
 
gst-launch-1.0 -e \
    ximagesrc display-name=:0.0 use-damage=false show-pointer=true xid=71303169 \
        ! capsfilter caps=video/x-raw,framerate=25/1 \
        ! videoconvert \
        ! videorate \
        ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=8 \
        ! video/x-h264, profile=baseline \
        ! mp4mux name=mux \
        ! filesink location=/home/flash/Videos/vokoscreenNG-2020-04-16_19-33-22.mp4

[vokoscreenNG] Stop record
radioButtonScreencastFullscreen=false
radioButtonScreencastWindow=false
radioButtonScreencastArea=true
checkBoxCameraOnOff=false
checkBoxCameraMirrorVertical=false
checkBoxCameraMirrorHorizontal=false
checkBoxCameraInvert=false
checkBoxCameraGray=false
checkBoxCameraMono=false
checkBoxCameraWindowFrame=false
checkBoxMouseCursorOnOff=false
checkboxAudioDevice-0=false
checkboxAudioDevice-1=false
checkBoxShowInSystray=true
checkBoxShowInSystrayAlternative=true
checkBoxMinimizedWhenRecordingStarts=false
checkBoxStartsMinimized=false
checkBoxResetAtNextStart=false
checkBoxLookForUpdates=true
checkBoxScale=false
checkBoxMagnifier=false
comboBoxCamera=
comboBoxFormat=mp4
comboBoxVideoCodec=x264
comboBoxx264Preset=superfast
comboBoxAudioCodec=mp3
comboBoxOnlineHelp=Automatically
comboBoxAreaSize=320 x 200 CGA 16 : 10
comboBoxScale=320 x 200 CGA 16 : 10
comboBoxScreencastScreen=DP-2 :  2560 x 1440
sliderCameraWindowSize=2
sliderVolume=70
sliderVideo=0
sliderX264=17
sliderOpenh264=23
sliderFrames=25
sliderLimitOfFreeDiskSpace=250
sliderShowInSystrayAlternative=48
sliderSecondWaitBeforeRecording=1
sliderHour=0
sliderMinute=0
sliderStopRecordingAfterHouers=0
sliderStopRecordingAfterMinutes=0
sliderStopRecordingAfterSeconds=15
sliderScreencastCountDown=0
sliderMagnification=2
lineEditVideoPath=/home/flash/Videos
[vokoscreenNG] Start record with: ximagesrc display-name=:0.0 use-damage=false show-pointer=true startx=620 starty=105 endx=2549 endy=1432 ! capsfilter caps=video/x-raw,framerate=25/1 ! videoconvert ! videorate ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=8 ! video/x-h264, profile=baseline ! mp4mux name=mux ! filesink location=/home/flash/Videos/vokoscreenNG-2020-04-16_19-34-48.mp4
 
gst-launch-1.0 -e \
    ximagesrc display-name=:0.0 use-damage=false show-pointer=true startx=620 starty=105 endx=2549 endy=1432 \
        ! capsfilter caps=video/x-raw,framerate=25/1 \
        ! videoconvert \
        ! videorate \
        ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=8 \
        ! video/x-h264, profile=baseline \
        ! mp4mux name=mux \
        ! filesink location=/home/flash/Videos/vokoscreenNG-2020-04-16_19-34-48.mp4

[vokoscreenNG] Stop record
</code>
</details>

**Comment by flash-me** [comment] 2020-04-16 17:40
When using the Window option and selecting a window on the second screen, everything works as expected

**Comment by tux93** [comment] 2020-04-16 18:01
Duplicate of #12 

Should be fixed with the next release

**Comment by flash-me** [comment] 2020-04-16 18:07
Alright! If you want, I could test out any beta or sth else and provide feedback

cheers
flash :zap:

**Comment by vkohaupt** [comment] 2020-04-22 07:20
Since yesterday there is a general installation package based on the last commit. You can use it to test the area.

**Closed as completed by vkohaupt** 2020-04-22 07:20 UTC
